name: new_core
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  device_info_plus: ^8.1.0
  internet_connection_checker: ^1.0.0+1
  google_fonts: ^4.0.3
  go_router: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.1.1
  formz: ^0.6.0
  regexpattern: ^2.1.0
  flutter_riverpod: ^2.3.2
  freezed: ^2.3.2
  cached_network_image: ^3.2.3
  flex_color_scheme: ^7.0.5

  equatable: ^2.0.5
  flutter_html: ^2.2.1
  html_unescape: ^2.0.0

#  path_parsing: any
#  file_picker: any
#  flutter_highlight: any
#  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  riverpod_lint: ^1.1.6
  custom_lint: ^0.3.2
  json_annotation: ^4.8.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


#  flutter pub add intl device_info_plus internet_connection_checker google_fonts go_router hive hive_flutter dio formz regexpattern flutter_riverpod freezed cached_network_image
#  flutter pub add json_serializable json_annotation riverpod_generator build_runner hive_generator riverpod_lint custom_lint --dev


